<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run()
    {
        // Seed Departments
        DB::table('departments')->insert([
            ['departmentname' => 'IT'],
            ['departmentname' => 'HR'],
            ['departmentname' => 'Finance'],
            ['departmentname' => 'Marketing'],
            ['departmentname' => 'Operations'],
            ['departmentname' => 'Sales'],
            ['departmentname' => 'Customer Support'],
            ['departmentname' => 'Logistics'],
            ['departmentname' => 'Procurement'],
            ['departmentname' => 'Legal'],
            ['departmentname' => 'R&D'],
            ['departmentname' => 'Training'],
            ['departmentname' => 'Compliance'],
            ['departmentname' => 'Business Development'],
            ['departmentname' => 'Corporate Affairs'],
            ['departmentname' => 'Investor Relations'],
            ['departmentname' => 'Risk Management'],
            ['departmentname' => 'Internal Audit'],
            ['departmentname' => 'Quality Assurance'],
            ['departmentname' => 'Public Relations'],
            ['departmentname' => 'Facility Management'],
            ['departmentname' => 'Health and Safety'],
            ['departmentname' => 'Environmental Services'],
            ['departmentname' => 'Community Engagement'],
            ['departmentname' => 'Product Management'],
            ['departmentname' => 'Software Development'],
            ['departmentname' => 'Hardware Engineering'],
            ['departmentname' => 'Data Analytics'],
            ['departmentname' => 'Machine Learning'],
            ['departmentname' => 'Cybersecurity'],
            ['departmentname' => 'Cloud Infrastructure'],
            ['departmentname' => 'DevOps'],
            ['departmentname' => 'Network Engineering'],
            ['departmentname' => 'Technical Support'],
            ['departmentname' => 'Content Creation'],
            ['departmentname' => 'Creative Design'],
            ['departmentname' => 'Event Management'],
            ['departmentname' => 'Social Media Management'],
            ['departmentname' => 'E-commerce'],
            ['departmentname' => 'Supply Chain'],
            ['departmentname' => 'Inventory Control'],
            ['departmentname' => 'Strategic Planning'],
            ['departmentname' => 'Knowledge Management'],
            ['departmentname' => 'Program Management'],
            ['departmentname' => 'Performance Management'],
            ['departmentname' => 'Partnerships'],
            ['departmentname' => 'Government Relations'],
            ['departmentname' => 'Human Capital'],
            ['departmentname' => 'Digital Marketing'],
            ['departmentname' => 'Corporate Security'],
            ['departmentname' => 'Customer Experience'],
            ['departmentname' => 'Product Development'],
            ['departmentname' => 'Brand Management'],
            ['departmentname' => 'Automation'],
            ['departmentname' => 'Innovation Lab'],
            ['departmentname' => 'Change Management'],
            ['departmentname' => 'Enterprise Architecture'],
            ['departmentname' => 'Mobile Development'],
            ['departmentname' => 'Web Development'],
            ['departmentname' => 'IT Support'],
            ['departmentname' => 'Knowledge Transfer'],
            ['departmentname' => 'Workforce Planning'],
            ['departmentname' => 'Compensation and Benefits'],
            ['departmentname' => 'Learning and Development'],
            ['departmentname' => 'Talent Acquisition'],
            ['departmentname' => 'Diversity and Inclusion'],
            ['departmentname' => 'Cultural Development'],
            ['departmentname' => 'Organizational Development'],
            ['departmentname' => 'Vendor Management'],
            ['departmentname' => 'Contract Management'],
            ['departmentname' => 'Shipping and Receiving'],
            ['departmentname' => 'Warehouse Management'],
            ['departmentname' => 'Fleet Management'],
            ['departmentname' => 'Energy Management'],
            ['departmentname' => 'Sustainability'],
            ['departmentname' => 'Disaster Recovery'],
            ['departmentname' => 'Incident Response'],
            ['departmentname' => 'Access Management'],
            ['departmentname' => 'Training Delivery'],
            ['departmentname' => 'Benefits Administration'],
            ['departmentname' => 'Cost Management'],
            ['departmentname' => 'Resource Allocation'],
            ['departmentname' => 'Corporate Communications'],
            ['departmentname' => 'Media Relations'],
            ['departmentname' => 'Advertising'],
            ['departmentname' => 'Merchandising'],
            ['departmentname' => 'Affiliate Marketing'],
            ['departmentname' => 'SEO Optimization'],
            ['departmentname' => 'Email Marketing'],
            ['departmentname' => 'Campaign Management'],
            ['departmentname' => 'Data Governance'],
            ['departmentname' => 'Business Intelligence'],
            ['departmentname' => 'Product Testing'],
            ['departmentname' => 'Manufacturing'],
            ['departmentname' => 'Assembly Line'],
            ['departmentname' => 'Maintenance'],
            ['departmentname' => 'Calibration'],
            ['departmentname' => 'Technical Writing'],
            ['departmentname' => 'Translation Services'],
            ['departmentname' => 'Customer Retention'],
        ]);

        // Seed Companies
        DB::table('companies')->insert([
            ['companyname' => 'PT. Maju Mundur', 'companycode' => 'MM001'],
            ['companyname' => 'PT. Sukses Selalu', 'companycode' => 'SS002'],
            ['companyname' => 'PT. Inovasi Teknologi', 'companycode' => 'IT001'],
            ['companyname' => 'PT. Digital Mandiri', 'companycode' => 'DM002'],
            ['companyname' => 'PT. Sinar Semesta', 'companycode' => 'SS003'],
            ['companyname' => 'PT. Riset Global', 'companycode' => 'RG004'],
            ['companyname' => 'PT. Kreatif Maju', 'companycode' => 'KM005'],
            ['companyname' => 'PT. Cipta Sukses', 'companycode' => 'CS006'],
            ['companyname' => 'PT. Mandiri Abadi', 'companycode' => 'MA007'],
            ['companyname' => 'PT. Artha Perkasa', 'companycode' => 'AP008'],
            ['companyname' => 'PT. Sejahtera Bersama', 'companycode' => 'SB009'],
            ['companyname' => 'PT. Global Indah', 'companycode' => 'GI010'],
            ['companyname' => 'PT. Visioner Teknologi', 'companycode' => 'VT011'],
            ['companyname' => 'PT. Prisma Nusantara', 'companycode' => 'PN012'],
            ['companyname' => 'PT. Solusi Sinergi', 'companycode' => 'SS013'],
            ['companyname' => 'PT. Inovasi Cemerlang', 'companycode' => 'IC014'],
            ['companyname' => 'PT. Gema Digital', 'companycode' => 'GD015'],
            ['companyname' => 'PT. Titan Raksasa', 'companycode' => 'TR016'],
            ['companyname' => 'PT. Citra Dinamika', 'companycode' => 'CD017'],
            ['companyname' => 'PT. Prima Energi', 'companycode' => 'PE018'],
            ['companyname' => 'PT. Agung Jaya', 'companycode' => 'AJ019'],
            ['companyname' => 'PT. Sumber Mitra', 'companycode' => 'SM020'],
        ]);

        // Seed Modules
        DB::table('modules')->insert([
            ['modulename' => 'FI'],
            ['modulename' => 'CO'],
            ['modulename' => 'FM'],
            ['modulename' => 'MM'],
            ['modulename' => 'PS'],
            ['modulename' => 'PP'],
            ['modulename' => 'HCM'],
            ['modulename' => 'SD'],
            ['modulename' => 'HRM'],
            ['modulename' => 'CRM'],
            ['modulename' => 'SCM'],
            ['modulename' => 'EWM'],
            ['modulename' => 'PPM'],
            ['modulename' => 'BI'],
            ['modulename' => 'BW'],
            ['modulename' => 'TM'],
            ['modulename' => 'QM'],
            ['modulename' => 'CS'],
            ['modulename' => 'WM'],
            ['modulename' => 'PLM'],
            ['modulename' => 'SRM'],
            ['modulename' => 'APO'],
            ['modulename' => 'PI'],
            ['modulename' => 'MDM'],
            ['modulename' => 'GRC'],
            ['modulename' => 'SEM'],
            ['modulename' => 'EHS'],
            ['modulename' => 'ISU'],
        ]);

        // Seed Categories
        DB::table('categories')->insert([
            ['categoryname' => 'SOFTWARE'],
            ['categoryname' => 'HARDWARE'],
            ['categoryname' => 'SAP'],
            ['categoryname' => 'INFRASTRUKTUR'],
            ['categoryname' => 'NETWORKING'],
            ['categoryname' => 'CLOUD COMPUTING'],
            ['categoryname' => 'DATA STORAGE'],
            ['categoryname' => 'AI SYSTEMS'],
            ['categoryname' => 'MACHINE LEARNING'],
            ['categoryname' => 'CYBERSECURITY'],
            ['categoryname' => 'DEVOPS'],
            ['categoryname' => 'WEB DEVELOPMENT'],
            ['categoryname' => 'MOBILE DEVELOPMENT'],
            ['categoryname' => 'ERP SYSTEMS'],
            ['categoryname' => 'CRM SYSTEMS'],
            ['categoryname' => 'PROJECT MANAGEMENT'],
            ['categoryname' => 'PRODUCTIVITY TOOLS'],
            ['categoryname' => 'DATABASE SYSTEMS'],
            ['categoryname' => 'BIG DATA'],
            ['categoryname' => 'ANALYTICS'],
            ['categoryname' => 'UI/UX DESIGN'],
            ['categoryname' => 'GAMING SOFTWARE'],
            ['categoryname' => 'OPERATING SYSTEMS'],
            ['categoryname' => 'OPEN SOURCE TOOLS'],
            ['categoryname' => 'E-COMMERCE'],
            ['categoryname' => 'SOCIAL MEDIA TOOLS'],
            ['categoryname' => 'GRAPHICS DESIGN'],
            ['categoryname' => 'VIDEO EDITING'],
            ['categoryname' => 'AUDIO EDITING'],
            ['categoryname' => 'VIRTUAL REALITY'],
            ['categoryname' => 'AUGMENTED REALITY'],
            ['categoryname' => 'AUTOMATION TOOLS'],
            ['categoryname' => 'API MANAGEMENT'],
            ['categoryname' => 'IOT SYSTEMS'],
            ['categoryname' => 'BLOCKCHAIN TECHNOLOGY'],
            ['categoryname' => 'ENTERPRISE SOLUTIONS'],
            ['categoryname' => 'FINTECH'],
            ['categoryname' => 'EDTECH'],
            ['categoryname' => 'HEALTHCARE IT'],
            ['categoryname' => 'LEGAL TECH'],
            ['categoryname' => 'TRAVEL TECH'],
            ['categoryname' => 'HR TECHNOLOGIES'],
            ['categoryname' => 'SUPPLY CHAIN'],
            ['categoryname' => 'WAREHOUSE MANAGEMENT'],
            ['categoryname' => 'LOGISTICS SYSTEMS'],
            ['categoryname' => 'DOCUMENT MANAGEMENT'],
            ['categoryname' => 'COLLABORATION TOOLS'],
            ['categoryname' => 'IT CONSULTING'],
            ['categoryname' => 'VIRTUALIZATION'],
            ['categoryname' => 'ROBOTICS'],
            ['categoryname' => 'BUSINESS INTELLIGENCE'],
            ['categoryname' => 'DIGITAL MARKETING'],
            ['categoryname' => 'EMAIL MARKETING'],
            ['categoryname' => 'SEO TOOLS'],
            ['categoryname' => 'CONTENT MANAGEMENT'],
            ['categoryname' => 'LEARNING MANAGEMENT'],
            ['categoryname' => 'SUPPLY CHAIN ANALYTICS'],
            ['categoryname' => 'CLOUD STORAGE'],
            ['categoryname' => 'COLLABORATION SOFTWARE'],
            ['categoryname' => 'REMOTE WORK TOOLS'],
            ['categoryname' => 'PRODUCT LIFECYCLE MANAGEMENT'],
            ['categoryname' => 'KNOWLEDGE MANAGEMENT'],
            ['categoryname' => 'IT ASSET MANAGEMENT'],
            ['categoryname' => 'CUSTOMER SUPPORT TOOLS'],
            ['categoryname' => 'PAYMENT SYSTEMS'],
            ['categoryname' => 'RETAIL SOLUTIONS'],
            ['categoryname' => 'POINT OF SALE'],
            ['categoryname' => 'HOSPITALITY TECH'],
            ['categoryname' => 'REAL ESTATE TECH'],
            ['categoryname' => 'EDUCATION TECHNOLOGY'],
            ['categoryname' => 'VIRTUAL MEETING TOOLS'],
            ['categoryname' => 'DATA VISUALIZATION'],
            ['categoryname' => 'REPORTING TOOLS'],
            ['categoryname' => 'FIELD SERVICE MANAGEMENT'],
            ['categoryname' => 'HELPDESK SOFTWARE'],
            ['categoryname' => 'NETWORK MONITORING'],
            ['categoryname' => 'INFRASTRUCTURE MANAGEMENT'],
            ['categoryname' => 'BUSINESS PROCESS AUTOMATION'],
            ['categoryname' => 'SOCIAL MEDIA MANAGEMENT'],
            ['categoryname' => 'CHATBOTS'],
            ['categoryname' => 'API INTEGRATION TOOLS'],
            ['categoryname' => 'WORKFLOW MANAGEMENT'],
            ['categoryname' => 'VIDEO CONFERENCING'],
            ['categoryname' => 'VIRTUAL DESKTOP INFRASTRUCTURE'],
            ['categoryname' => 'CYBER THREAT ANALYSIS'],
            ['categoryname' => 'IDENTITY MANAGEMENT'],
            ['categoryname' => 'ACCESS CONTROL'],
            ['categoryname' => 'FILE SHARING TOOLS'],
            ['categoryname' => 'ONLINE SECURITY TOOLS'],
            ['categoryname' => 'SERVER MANAGEMENT'],
            ['categoryname' => 'BACKUP AND RECOVERY'],
            ['categoryname' => 'DISASTER MANAGEMENT SYSTEMS'],
            ['categoryname' => 'SECURITY OPERATIONS CENTER'],
            ['categoryname' => 'EMAIL SECURITY'],
            ['categoryname' => 'DATA ENCRYPTION'],
            ['categoryname' => 'DIGITAL RIGHTS MANAGEMENT'],
            ['categoryname' => 'SOFTWARE TESTING'],
            ['categoryname' => 'BUG TRACKING TOOLS'],
            ['categoryname' => 'VERSION CONTROL SYSTEMS'],
            ['categoryname' => 'AGILE PROJECT TOOLS'],
        ]);

        // Seed Priorities
        DB::table('priorities')->insert([
            ['priorityname' => 'LOW'],
            ['priorityname' => 'MEDIUM'],
            ['priorityname' => 'HIGH'],
        ]);

        // Seed Jhonlins
        DB::table('users')->insert([
            [
                'name' => 'Admin',
                'email' => 'admin@example.com',
                'password' => bcrypt('Jhonlin@123'),
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'phone' => '08232323111',
                'level' => 1,
                'iddepartment' => 1,
                'idcompany' => 1,
            ],
            [
                'name' => 'Budi Santoso',
                'email' => 'budi.santoso@gmail.com',
                'password' => bcrypt('Jhonlin@123'),
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'phone' => '08252323111',
                'level' => 2,
                'iddepartment' => 1,
                'idcompany' => 1,
            ],
            [
                'name' => 'Siti Aminah',
                'email' => 'siti.aminah@gmail.com',
                'password' => bcrypt('Jhonlin@123'),
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'phone' => '0823232313',
                'level' => 2,
                'iddepartment' => 2,
                'idcompany' => 1,
            ],
            [
                'name' => 'Andi Prasetyo',
                'email' => 'andi.prasetyo@gmail.com',
                'password' => bcrypt('Jhonlin@123'),
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'phone' => '08232323311',
                'level' => 2,
                'iddepartment' => 3,
                'idcompany' => 2,
            ],
            [
                'name' => 'Dewi Lestari',
                'email' => 'dewi.lestari@gmail.com',
                'password' => bcrypt('Jhonlin@123'),
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'phone' => '08232323621',
                'level' => 2,
                'iddepartment' => 4,
                'idcompany' => 2,
            ],
            [
                'name' => 'Ahmad Ramadhan',
                'email' => 'ahmad.ramadhan@gmail.com',
                'password' => bcrypt('Jhonlin@123'),
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'phone' => '08212345678',
                'level' => 2,
                'iddepartment' => 1,
                'idcompany' => 1,
            ],
            [
                'name' => 'Nurul Hidayati',
                'email' => 'nurul.hidayati@gmail.com',
                'password' => bcrypt('Jhonlin@123'),
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'phone' => '08298765432',
                'level' => 2,
                'iddepartment' => 2,
                'idcompany' => 1,
            ],
            [
                'name' => 'Hendri Setiawan',
                'email' => 'hendri.setiawan@gmail.com',
                'password' => bcrypt('Jhonlin@123'),
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'phone' => '08287654321',
                'level' => 2,
                'iddepartment' => 3,
                'idcompany' => 2,
            ],
            [
                'name' => 'Rini Kartika',
                'email' => 'rini.kartika@gmail.com',
                'password' => bcrypt('Jhonlin@123'),
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'phone' => '08276543219',
                'level' => 2,
                'iddepartment' => 4,
                'idcompany' => 2,
            ],
            [
                'name' => 'Fajar Maulana',
                'email' => 'helpdesk@gmail.com',
                'password' => bcrypt('Jhonlin@123'),
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'phone' => '08265432198',
                'level' => 2,
                'iddepartment' => 5,
                'idcompany' => 2,
            ],
            [
                'name' => 'PIC Testing',
                'email' => 'PIC1@gmail.com',
                'password' => bcrypt('Jhonlin@123'),
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'phone' => '08265432198',
                'level' => 3,
                'iddepartment' => 5,
                'idcompany' => 2,
            ],
            [
                'name' => 'Harlan Muradi',
                'email' => 'harlanmuradi@gmail.com',
                'password' => bcrypt('Jhonlin@123'),
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'phone' => '08265432198',
                'level' => 4,
                'iddepartment' => 5,
                'idcompany' => 2,
            ],
        ]);
    }
}
